services:
  treasury_db:
    container_name: treasury_db
    image: postgres:15.2-alpine
    restart: unless-stopped
    volumes:
      - treasury_db:/var/lib/postgresql/data
    env_file:
      - .env
    shm_size: 1gb
  
  treasury_api:
    container_name: treasury_api
    build: .
    restart: unless-stopped
    depends_on:
      - treasury_db
    volumes:
      - .:/app
      - ./static:/app/treasury/static
    ports:
      - "127.0.0.1:8035:80"
    command: ["python", "/app/treasury/manage.py", "runserver", "0:80"]
    env_file:
      - .env
  
  treasury_worker:
    container_name: treasury_worker
    build: .
    working_dir: /app/treasury
    command: ["celery", "-A", "treasury", "worker", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - treasury_db
      - treasury_redis
    env_file:
      - .env

  treasury_beat:
    container_name: treasury_beat
    build: .
    working_dir: /app/treasury
    command: ["celery", "-A", "treasury", "beat", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - treasury_db
      - treasury_redis
    env_file:
      - .env

  treasury_redis:
    container_name : treasury_redis
    image: redis:6.2-alpine
    restart: unless-stopped

volumes:
  treasury_db: