# Generated by Django 4.1 on 2023-02-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_vocabulary_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
